appName=AndroidTestHelper
versionName=0.1.1
author=floatingmuseum
vendor=Floating Museum
description=Desktop console for testing Android devices with bundled ADB, scrcpy, and platform-tools.
windowsUpgradeUuid=4f3b4f2f-8730-4f23-8f87-7c02bd9156cb
macosBundleID=com.floatingmuseum.android.test.helper
linuxPackageID=com.floatingmuseum.android.test.helper
